### ISSUE TITLE
ypeError: moment is not a function

### ISSUE THREAD

**Issue by subcero123** [abhishekjain12/ngx-time-scheduler#35]
core.mjs:11760 ERROR TypeError: moment is not a function
    at new NgxTimeSchedulerComponent (ngx-time-scheduler.mjs:113:22)
    at NodeInjectorFactory.NgxTimeSchedulerComponent_Factory [as factory] (ngx-time-scheduler.mjs:363:31)
    at getNodeInjectable (core.mjs:4391:44)
    at instantiateAllDirectives (core.mjs:12800:27)
    at createDirectivesInstances (core.mjs:12216:5)
    at ɵɵelementStart (core.mjs:22085:9)
    at ɵɵelement (core.mjs:22143:5)
    at AgendaComponent_Template (agenda.component.html:4:18)
    at executeTemplate (core.mjs:12181:9)
    at renderView (core.mjs:15243:13)
    
    Already installed moment, looks like is not recognizing moment of my angular project (can use it in components)

**Comment by skyplane23** [comment]
Hi! Did you found a solution or workaround for this?
